//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbeariaWebApi.PrestadorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestador", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Prestador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Agendamento[] AgendamentoField;
        
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Venda[] VendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string especialidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idespecialidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Agendamento[] Agendamento {
            get {
                return this.AgendamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendamentoField, value) != true)) {
                    this.AgendamentoField = value;
                    this.RaisePropertyChanged("Agendamento");
                }
            }
        }
        
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Venda[] Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string especialidade {
            get {
                return this.especialidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.especialidadeField, value) != true)) {
                    this.especialidadeField = value;
                    this.RaisePropertyChanged("especialidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idespecialidade {
            get {
                return this.idespecialidadeField;
            }
            set {
                if ((this.idespecialidadeField.Equals(value) != true)) {
                    this.idespecialidadeField = value;
                    this.RaisePropertyChanged("idespecialidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Especialidade", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Especialidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Prestador[] PrestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Prestador[] Prestador {
            get {
                return this.PrestadorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrestadorField, value) != true)) {
                    this.PrestadorField = value;
                    this.RaisePropertyChanged("Prestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agendamento", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Agendamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Prestador PrestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime horarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprestadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Prestador Prestador {
            get {
                return this.PrestadorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrestadorField, value) != true)) {
                    this.PrestadorField = value;
                    this.RaisePropertyChanged("Prestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime horario {
            get {
                return this.horarioField;
            }
            set {
                if ((this.horarioField.Equals(value) != true)) {
                    this.horarioField = value;
                    this.RaisePropertyChanged("horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((this.idclienteField.Equals(value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprestador {
            get {
                return this.idprestadorField;
            }
            set {
                if ((this.idprestadorField.Equals(value) != true)) {
                    this.idprestadorField = value;
                    this.RaisePropertyChanged("idprestador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venda", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Prestador PrestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.ProdutoVenda[] ProdutoVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.ServicoVenda[] ServicoVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Prestador Prestador {
            get {
                return this.PrestadorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrestadorField, value) != true)) {
                    this.PrestadorField = value;
                    this.RaisePropertyChanged("Prestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.ProdutoVenda[] ProdutoVenda {
            get {
                return this.ProdutoVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoVendaField, value) != true)) {
                    this.ProdutoVendaField = value;
                    this.RaisePropertyChanged("ProdutoVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.ServicoVenda[] ServicoVenda {
            get {
                return this.ServicoVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoVendaField, value) != true)) {
                    this.ServicoVendaField = value;
                    this.RaisePropertyChanged("ServicoVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((this.idclienteField.Equals(value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprestador {
            get {
                return this.idprestadorField;
            }
            set {
                if ((this.idprestadorField.Equals(value) != true)) {
                    this.idprestadorField = value;
                    this.RaisePropertyChanged("idprestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Agendamento[] AgendamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Sexo SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Venda[] VendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idsexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Agendamento[] Agendamento {
            get {
                return this.AgendamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendamentoField, value) != true)) {
                    this.AgendamentoField = value;
                    this.RaisePropertyChanged("Agendamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Sexo Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Venda[] Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsexo {
            get {
                return this.idsexoField;
            }
            set {
                if ((this.idsexoField.Equals(value) != true)) {
                    this.idsexoField = value;
                    this.RaisePropertyChanged("idsexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sexo", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Sexo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Cliente[] ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexo1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Cliente[] Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo1 {
            get {
                return this.sexo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.sexo1Field, value) != true)) {
                    this.sexo1Field = value;
                    this.RaisePropertyChanged("sexo1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoVenda", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class ProdutoVenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Venda VendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprodutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idvendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Venda Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idproduto {
            get {
                return this.idprodutoField;
            }
            set {
                if ((this.idprodutoField.Equals(value) != true)) {
                    this.idprodutoField = value;
                    this.RaisePropertyChanged("idproduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idvenda {
            get {
                return this.idvendaField;
            }
            set {
                if ((this.idvendaField.Equals(value) != true)) {
                    this.idvendaField = value;
                    this.RaisePropertyChanged("idvenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicoVenda", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class ServicoVenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Servico ServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.Venda VendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idservicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idvendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Servico Servico {
            get {
                return this.ServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoField, value) != true)) {
                    this.ServicoField = value;
                    this.RaisePropertyChanged("Servico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.Venda Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idservico {
            get {
                return this.idservicoField;
            }
            set {
                if ((this.idservicoField.Equals(value) != true)) {
                    this.idservicoField = value;
                    this.RaisePropertyChanged("idservico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idvenda {
            get {
                return this.idvendaField;
            }
            set {
                if ((this.idvendaField.Equals(value) != true)) {
                    this.idvendaField = value;
                    this.RaisePropertyChanged("idvenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.ProdutoVenda[] ProdutoVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.ProdutoVenda[] ProdutoVenda {
            get {
                return this.ProdutoVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoVendaField, value) != true)) {
                    this.ProdutoVendaField = value;
                    this.RaisePropertyChanged("ProdutoVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double preco {
            get {
                return this.precoField;
            }
            set {
                if ((this.precoField.Equals(value) != true)) {
                    this.precoField = value;
                    this.RaisePropertyChanged("preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servico", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Servico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BarbeariaWebApi.PrestadorServiceReference.ServicoVenda[] ServicoVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BarbeariaWebApi.PrestadorServiceReference.ServicoVenda[] ServicoVenda {
            get {
                return this.ServicoVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoVendaField, value) != true)) {
                    this.ServicoVendaField = value;
                    this.RaisePropertyChanged("ServicoVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double preco {
            get {
                return this.precoField;
            }
            set {
                if ((this.precoField.Equals(value) != true)) {
                    this.precoField = value;
                    this.RaisePropertyChanged("preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrestadorServiceReference.IServicePrestador")]
    public interface IServicePrestador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/FindAll", ReplyAction="http://tempuri.org/IServicePrestador/FindAllResponse")]
        BarbeariaWebApi.PrestadorServiceReference.Prestador[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/FindAll", ReplyAction="http://tempuri.org/IServicePrestador/FindAllResponse")]
        System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Find", ReplyAction="http://tempuri.org/IServicePrestador/FindResponse")]
        BarbeariaWebApi.PrestadorServiceReference.Prestador Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Find", ReplyAction="http://tempuri.org/IServicePrestador/FindResponse")]
        System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/New", ReplyAction="http://tempuri.org/IServicePrestador/NewResponse")]
        BarbeariaWebApi.PrestadorServiceReference.Prestador New(BarbeariaWebApi.PrestadorServiceReference.Prestador prestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/New", ReplyAction="http://tempuri.org/IServicePrestador/NewResponse")]
        System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> NewAsync(BarbeariaWebApi.PrestadorServiceReference.Prestador prestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Update", ReplyAction="http://tempuri.org/IServicePrestador/UpdateResponse")]
        BarbeariaWebApi.PrestadorServiceReference.Prestador Update(int id, BarbeariaWebApi.PrestadorServiceReference.Prestador prestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Update", ReplyAction="http://tempuri.org/IServicePrestador/UpdateResponse")]
        System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> UpdateAsync(int id, BarbeariaWebApi.PrestadorServiceReference.Prestador prestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Delete", ReplyAction="http://tempuri.org/IServicePrestador/DeleteResponse")]
        BarbeariaWebApi.PrestadorServiceReference.Prestador Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePrestador/Delete", ReplyAction="http://tempuri.org/IServicePrestador/DeleteResponse")]
        System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePrestadorChannel : BarbeariaWebApi.PrestadorServiceReference.IServicePrestador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePrestadorClient : System.ServiceModel.ClientBase<BarbeariaWebApi.PrestadorServiceReference.IServicePrestador>, BarbeariaWebApi.PrestadorServiceReference.IServicePrestador {
        
        public ServicePrestadorClient() {
        }
        
        public ServicePrestadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePrestadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePrestadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePrestadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BarbeariaWebApi.PrestadorServiceReference.Prestador[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public BarbeariaWebApi.PrestadorServiceReference.Prestador Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public BarbeariaWebApi.PrestadorServiceReference.Prestador New(BarbeariaWebApi.PrestadorServiceReference.Prestador prestador) {
            return base.Channel.New(prestador);
        }
        
        public System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> NewAsync(BarbeariaWebApi.PrestadorServiceReference.Prestador prestador) {
            return base.Channel.NewAsync(prestador);
        }
        
        public BarbeariaWebApi.PrestadorServiceReference.Prestador Update(int id, BarbeariaWebApi.PrestadorServiceReference.Prestador prestador) {
            return base.Channel.Update(id, prestador);
        }
        
        public System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> UpdateAsync(int id, BarbeariaWebApi.PrestadorServiceReference.Prestador prestador) {
            return base.Channel.UpdateAsync(id, prestador);
        }
        
        public BarbeariaWebApi.PrestadorServiceReference.Prestador Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<BarbeariaWebApi.PrestadorServiceReference.Prestador> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
